name: CI
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
jobs:

  tidy:
    name: Tidy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0 # fetch all history for all branches and tags
      - run: ./ci/test_tidy.sh

  deploy:
    name: Latex Build and Deploy
    runs-on: ubuntu-22.04
    env:
      # RE https://stackoverflow.com/a/40184923/17332200
      PIP_NO_CACHE_DIR: 1
    container:
      image: ghcr.io/mmore500/teximage:sha-77b8179
      options: --user root
    permissions:
      contents: write
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build LaTeX document
        run: |
          trap 'cat *.log || true >> "$GITHUB_OUTPUT"' EXIT
          make
      - name: Prepare deploy directory
        run: |
          mkdir -p deploy
          cp *-draft.pdf deploy/
          echo "<html><body><a href=\"$(cd deploy && ls *-draft.pdf)\">Download Manuscript Draft [PDF]</a></body></html>" > deploy/index.html
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: manuscript
          path: '*-draft.pdf'
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
