name: CI
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
jobs:

  tidy:
    name: Tidy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0 # fetch all history for all branches and tags
      - run: bash ./ci/test_tidy.sh

  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0 # fetch all history for all branches and tags
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: 'build-base'
          root_file: main.tex
          post_compile: 'make'
      - run: ls
      - run: mkdir deploy
      - run: cp workspace-draft.pdf deploy/conduit-quality-of-service-writeup-draft.pdf
      # disabled because output file size is too large (>100mb)
      # - uses: JamesIves/github-pages-deploy-action@4.0.0
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: deploy # The folder the action should deploy.
      #     clean: true # Automatically remove deleted files from the deploy branch
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: deploy/conduit-quality-of-service-writeup-draft.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: deploy/conduit-quality-of-service-writeup-draft.pdf
